<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses'=>'IndexController@index',
    'as'=>'index'
]);

Auth::routes();
Route::get('/Membership/Plans',[
    'uses'=>'MembershipController@index',
    'as'=>'membership'
]);
Route::get('/Bronze',[
    'uses'=>'MembershipController@Bronze',
    'as'=>'bronze'
]);
Route::get('/Silver',[
    'uses'=>'MembershipController@Silver',
    'as'=>'silver'
]);
Route::get('/Gold',[
    'uses'=>'MembershipController@Gold',
    'as'=>'gold'
]);
Route::get('/Dashboard/Index', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/Account/Index',[
        'uses'=>'ProfileController@index',
        'as'=>'account'
    ]);
    Route::Post('/Account/Bio',[
        'uses'=>'ProfileController@Bio',
        'as'=>'Bio'
    ]);
    Route::Post('/Account/Photo',[
        'uses'=>'ProfileController@Photo',
        'as'=>'Photo'
    ]);
    Route::Post('/Account/Bio/Update/{UserId}',[
        'uses'=>'ProfileController@update',
        'as'=>'EditBio'
    ]);
    Route::get('/Post/Project',[
        'uses'=>'ProjectsController@create',
        'as'=>'projects.add'
    ]);
    Route::get('/Projects/View',[
        'uses'=>'ProjectsController@view',
        'as'=>'projects.view'
    ]);
    Route::get('/Projects/Index',[
        'uses'=>'JobsController@index',
        'as'=>'jobs'
    ]);
    Route::get('/Membership/Profiles',[
        'uses'=>'MembershipController@newPlan',
        'as'=>'MembershipProfiles'
    ]);
    Route::get('/Payments/Profiles',[
        'uses'=>'PaymentsController@platform',
        'as'=>'payments'
    ]);
    Route::post('/Payments/Plaforms',[
        'uses'=>'PaymentsController@storePlatforms',
        'as'=>'platform.post'
    ]);
    Route::get('/Pay/WithPaypal/{Profile}',[
        'uses'=>'PaymentsController@PaywithPaypal',
        'as'=>'paypal'
    ]);
    Route::get('/Platform/Delete/{id}',[
        'uses'=>'PaymentsController@destroy',
        'as'=>'platform.delete'
    ]);
    Route::post('/Plans/Post',[
        'uses'=>'MembershipController@store',
        'as'=>'plans.post'
    ]);
    Route::get('/Plan/Delete/{PlanId}',[
        'uses'=>'MembershipController@destroy',
        'as'=>'plans.delete'
    ]);
    Route::get('/Accept/{ChatId}',[
        'uses'=>'ProjectsController@accept',
        'as'=>'accept'
    ]);
    Route::get('/Milestone/Release/{ChatId}',[
        'uses'=>'ProjectsController@Release',
        'as'=>'release'
    ]);
    Route::get('/Running/Contracts',[
        'uses'=>'JobsController@Contracts',
        'as'=>'running'
    ]);
    Route::get('/Reject/{ChatId}',[
        'uses'=>'ProjectsController@reject',
        'as'=>'reject'
    ]);
    Route::get('/Projects/Completed',[
        'uses'=>'ProjectsController@completed',
        'as'=>'projects.completed'
    ]);
    Route::get('/Job/Id/{projectId}',[
        'uses'=>'ProjectsController@show',
        'as'=>'singleProject'
    ]);
    Route::get('/Suspend/Bids/{slug}',[
        'uses'=>'ProjectsController@close',
        'as'=>'close'
    ]);
    Route::get('/Complete/Project/{slug}',[
        'uses'=>'ProjectsController@complete',
        'as'=>'complete'
    ]);
    Route::post('/Milestone/Create/{ProjectId}',[
        'uses'=>'ProjectsController@milestone',
        'as'=>'milestone'
    ]);
    Route::post('/Hours/Track/{ProjectId}',[
        'uses'=>'ProjectsController@TrackHours',
        'as'=>'hours'
    ]);
    Route::get('/Project/Hours/{ProjectId}',[
        'uses'=>'ProjectsController@track',
        'as'=>'project.hours'
    ]);
    Route::get('/Award/Project/{ChatId}',[
        'uses'=>'ProjectsController@award',
        'as'=>'award'
    ]);
    Route::get('/Complete/Contract/{ChatId}',[
        'uses'=>'ProjectsController@completeContract',
        'as'=>'completeContract'
    ]);
    Route::get('/Contract/Complete/{ProjectId}/{ChatId}',[
        'uses'=>'ProjectsController@AgreeContract',
        'as'=>'AgreeComplete'
    ]);
    Route::get('/Contract/NoComplete/{ProjectId}',[
        'uses'=>'ProjectsController@NoComplete',
        'as'=>'NoComplete'
    ]);
    Route::get('/Account/Profile',[
        'uses'=>'AccountsController@index',
        'as'=>'profile'
    ]);
    Route::get('/Terminate/Contract/{ChatId}',[
        'uses'=>'ProjectsController@terminateContract',
        'as'=>'terminateContract'
    ]);
    Route::get('/Submit/Proposal/{projectId}',[
        'uses'=>'JobsController@Proposal',
        'as'=>'proposalPost'
    ]);
    Route::get('/Job/Views/{projectId}',[
        'uses'=>'JobsController@show',
        'as'=>'singleJob'
    ]);
    Route::post('/Project/Post',[
        'uses'=>'ProjectsController@store',
        'as'=>'project.bpost'
    ]);
    Route::post('/Approve/Project/{ProjectId}',[
        'uses'=>'ProjectsController@approve',
        'as'=>'approve'
    ]);
    Route::post('/Reject/Project/{ProjectId}',[
        'uses'=>'ProjectsController@reject',
        'as'=>'reject'
    ]);
    Route::post('/Project/Proposal/{Id}',[
        'uses'=>'ProposalsController@store',
        'as'=>'proposal.post'
    ]);
    Route::get('/Proposed/Jobs',[
        'uses'=>'ProposalsController@proposed',
        'as'=>'proposed'
    ]);
    Route::get('/Proposal/Retract/{ProjectId}',[
        'uses'=>'ProposalsController@retract',
        'as'=>'retract'
    ]);
    Route::get('/Message/Project/{ProjectId}/{UserId}',[
        'uses'=>'MessagesController@index',
        'as'=>'message'
    ]);
    Route::get('/Messages/Projects/{ChatId}',[
        'uses'=>'MessagesController@From',
        'as'=>'messageFrom'
    ]);
    Route::get('/Messages/Sent/{ChatId}',[
        'uses'=>'MessagesController@Sent',
        'as'=>'Tomessage'
    ]);
    Route::post('/Messages/{UserId}/{ProjectId}',[
        'uses'=>'MessagesController@store',
        'as'=>'message.post'
    ]);
    Route::get('/Payments/Statements',[
        'uses'=>'PaymentsController@index',
        'as'=>'statement'
    ]);
    Route::get('/Withdrawal/',[
        'uses'=>'PaymentsController@withdraw',
        'as'=>'withdraw'
    ]);
});